---
title: "Ten Steps to Reproducible Research in R / Bioconductor"
author: "Thomas Girke, Vincent Carey, Martin Morgan"
date: "`r doc_date()`"
package: "`r pkg_ver('BiocStyle')`"
abstract: >
    Reproduciblity is a essential component of the scientific
    endeavor. Reproducibility in bioinformatic and statistical
    analysis is particularly challenging, and particularly amenable to
    practical solution. Here we outline ten steps, and a few
    mis-steps, to enhance the reproducibility of analyses developed
    using _R_ / _Bioconductor_ software.
vignette: >
    %\VignetteIndexEntry{Ten Steps to Reproducible Research in R / Bioconductor}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
output: 
    BiocStyle::html_document
---

# Why bother?

- Good science
- Research integrity -- acknowledging and correcting errors
- ...

# Ten steps...

## Analysis

1. 'Literate' documents (minimally, documented scripts) that describe
   analytic steps in a way that requires actual
   evaluation. Specification of software versions.

2. Software versioning, e.g., via `sessionInfo()`

3.

4.

## Work flows

5. Track provenance, from A to Z to A. Capture parameters of upstream
   steps. Propagate parameters to down-stream steps.

6.

7. `Docker` or other images capturing system requirements. Risk: lack
   of care in creation and curation of image. Although the container
   replicates the exact work flow, it is not useful to others wishing
   to perform similar analyses.

## Software development

8. Metadata is data. Value of computing on information about primary
   data. The `SummarizedExperiment` class.

9. Defined data structures for re-use and interoperability. Heavy
   software use is is more likely surface errors. Minimizing
   opportunities for error-prone transformation between
   representations.

10. Templates for input and output steps. E.g., the
    `SummarizedExperiment` class can be thought of as three data base
    tables (sheets in a spreadsheet) corresponding to the main assay
    data, the column (sample description) data, and the row (feature)
    data.

# ... and some mis-steps

1. Graphical User Interfaces

2. Within the _Bioconductor_ project: not all package 'tar' balls are
   available.

3.

# Appendix

```{r}
sessionInfo()
```
